<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.SCUO3Li' shared service.

return $this->privates['service_locator.SCUO3Li'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('logger' => function () {
    return ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService());
}));
