<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\GreetingGenerator' shared autowired service.

include_once $this->targetDirs[3].'/src/GreetingGenerator.php';

return $this->privates['App\GreetingGenerator'] = new \App\GreetingGenerator();
