<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.listener.view.validate' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/Symfony/Validator/EventListener/ValidateListener.php';

return $this->privates['api_platform.listener.view.validate'] = new \ApiPlatform\Core\Bridge\Symfony\Validator\EventListener\ValidateListener(($this->services['validator'] ?? $this->getValidatorService()), ($this->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), $this);
